dist: trusty
sudo: requires
before_install:
  - sudo apt-get -qq update && sudo apt-get install -y --no install-recommends textlive-latex-recommended textlive-latex-recommended textlive-latex-extra latex-xcolor
script:
  - mkdir build
  - pdflatex -interaction=nonstopmode -halt-on-error -output-directory build index.tex &&
    (bibtex build/index || true) &&
    pdflatex -interaction=nonstopmode -halt-on-error -output-directory build index.tex &&
    pdflatex -interaction=nonstopmode -halt-on-error -output-directory build index.tex
after_success:
  - mkdir deploy
  - cp build/*.pdf deploy/
after_failure:
  - cat build/index.log
deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  local_dir: deploy
  target_branch: pdfs
  skip_cleanup: true
  on:
    branch: master
  
